apiVersion: v1
kind: Service
metadata:
  name: hls-go
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: hls-go
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hls-go
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app: hls-go
  template:
    metadata:
      labels:
        app: hls-go
    spec:
      containers:
        - name: hls-go
          image: rodrigodev/hls_go:latest
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 8080